apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgchart
  labels:
    app: orgchart
spec:
  selector:
    matchLabels:
      app: orgchart
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'myapp'
        vault.hashicorp.com/agent-inject-secret-database-config.txt: 'secret/myapp/db-config'

        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "secret/myapp/db-config" -}}
          postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:{{ .Data.data.db_name }}//{{ .Data.data.url }}
          {{- end -}}

      labels:
        app: orgchart
    spec:
      containers:
        - name: orgchart
          image: jweissig/app:0.0.1